Unify all the function names, variables, names and builtins usage

diff --git a/enroot b/enroot
--- a/enroot
+++ b/enroot
@@ -5,29 +5,27 @@
 set -euo pipefail
 shopt -s lastpipe
 
-readonly XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"
-readonly XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
-readonly XDG_CACHE_HOME="${XDG_CACHE_HOME:-${HOME}/.cache}"
-readonly XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run}"
+default() { eval export "$1=\${$1:-${2-}}"; }
 
-readonly ENROOT_VERSION="@version@"
+default XDG_DATA_HOME        "${HOME:-~}/.local/share"
+default XDG_CONFIG_HOME      "${HOME:-~}/.config"
+default XDG_CACHE_HOME       "${HOME:-~}/.cache"
+default XDG_RUNTIME_DIR      "/run"
 
-config() { eval "export $1=\${$1:-${2-}}"; }
+default ENROOT_LIBEXEC_PATH  "@libexecdir@"
+default ENROOT_SYSCONF_PATH  "@sysconfdir@"
+default ENROOT_CONFIG_PATH   "${XDG_CONFIG_HOME}/enroot"
+default ENROOT_CACHE_PATH    "${XDG_CACHE_HOME}/enroot"
+default ENROOT_DATA_PATH     "${XDG_DATA_HOME}/enroot"
+default ENROOT_RUNTIME_PATH  "${XDG_RUNTIME_DIR}/enroot"
 
-config ENROOT_LIBEXEC_PATH  "@libexecdir@"
-config ENROOT_SYSCONF_PATH  "@sysconfdir@"
-config ENROOT_CONFIG_PATH   "${XDG_CONFIG_HOME}/enroot"
-config ENROOT_CACHE_PATH    "${XDG_CACHE_HOME}/enroot"
-config ENROOT_DATA_PATH     "${XDG_DATA_HOME}/enroot"
-config ENROOT_RUNTIME_PATH  "${XDG_RUNTIME_DIR}/enroot"
-
-config ENROOT_GZIP_PROG     "$(command -v pigz > /dev/null && echo pigz || echo gzip)"
-config ENROOT_SQUASH_OPTS   "-comp lzo -noD"
-config ENROOT_INIT_SHELL    "/bin/sh"
-config ENROOT_ROOTFS_RW
-config ENROOT_REMAP_ROOT
-config ENROOT_BUNDLE_ALL
-config ENROOT_BUNDLE_SUM
+default ENROOT_GZIP_PROG     "$(command -v pigz > /dev/null && echo pigz || echo gzip)"
+default ENROOT_SQUASH_OPTS   "-comp lzo -noD"
+default ENROOT_LOGIN_SHELL   "/bin/sh"
+default ENROOT_ROOTFS_RW     # unset
+default ENROOT_REMAP_ROOT    # unset
+default ENROOT_BUNDLE_ALL    # unset
+default ENROOT_BUNDLE_SUM    # unset
 
 (umask 077 && mkdir -p "${ENROOT_CONFIG_PATH}" "${ENROOT_CACHE_PATH}" "${ENROOT_DATA_PATH}" "${ENROOT_RUNTIME_PATH}")
 
@@ -36,7 +34,7 @@ source "${ENROOT_LIBEXEC_PATH}/docker.sh"
 source "${ENROOT_LIBEXEC_PATH}/runtime.sh"
 
 for cmd in curl jq parallel mksquashfs unsquashfs tar "${ENROOT_GZIP_PROG}"; do
-    command -v "${cmd}" > /dev/null || err "Command not found: ${cmd}"
+    command -v "${cmd}" > /dev/null || common::err "Command not found: ${cmd}"
 done
 
 enroot::usage() {
@@ -57,7 +55,7 @@ enroot::usage() {
 }
 
 enroot::version() {
-    echo "${ENROOT_VERSION}"
+    printf "%s\n" "@version@"
 }
 
 enroot::import() {
@@ -72,15 +70,11 @@ enroot::import() {
             shift 2
             ;;
         --)
-            shift
-            break
-            ;;
+            shift; break ;;
         -?*)
-            enroot::usage
-            ;;
+            enroot::usage ;;
         *)
-            break
-            ;;
+            break ;;
         esac
     done
     if [ $# -lt 1 ]; then
@@ -103,15 +97,11 @@ enroot::export() {
             shift 2
             ;;
         --)
-            shift
-            break
-            ;;
+            shift; break ;;
         -?*)
-            enroot::usage
-            ;;
+            enroot::usage ;;
         *)
-            break
-            ;;
+            break ;;
         esac
     done
     if [ $# -lt 1 ]; then
@@ -134,15 +124,11 @@ enroot::create() {
             shift 2
             ;;
         --)
-            shift
-            break
-            ;;
+            shift; break ;;
         -?*)
-            enroot::usage
-            ;;
+            enroot::usage ;;
         *)
-            break
-            ;;
+            break ;;
         esac
     done
     if [ $# -lt 1 ]; then
@@ -173,15 +159,11 @@ enroot::start() {
             shift
             ;;
         --)
-            shift
-            break
-            ;;
+            shift; break ;;
         -?*)
-            enroot::usage
-            ;;
+            enroot::usage ;;
         *)
-            break
-            ;;
+            break ;;
         esac
     done
     if [ $# -lt 1 ]; then
@@ -203,15 +185,11 @@ enroot::list() {
             shift
             ;;
         --)
-            shift
-            break
-            ;;
+            shift; break ;;
         -?*)
-            enroot::usage
-            ;;
+            enroot::usage ;;
         *)
-            break
-            ;;
+            break ;;
         esac
     done
 
@@ -229,15 +207,11 @@ enroot::remove() {
             shift
             ;;
         --)
-            shift
-            break
-            ;;
+            shift; break ;;
         -?*)
-            enroot::usage
-            ;;
+            enroot::usage ;;
         *)
-            break
-            ;;
+            break ;;
         esac
     done
     if [ $# -lt 1 ]; then
@@ -281,15 +255,11 @@ enroot::bundle() {
             shift 2
             ;;
         --)
-            shift
-            break
-            ;;
+            shift; break ;;
         -?*)
-            enroot::usage
-            ;;
+            enroot::usage ;;
         *)
-            break
-            ;;
+            break ;;
         esac
     done
     if [ $# -lt 1 ]; then
@@ -307,32 +277,23 @@ command="$1"; shift
 
 case "${command}" in
 version)
-    enroot::version "$@"
-    ;;
+    enroot::version "$@" ;;
 import)
-    enroot::import "$@"
-    ;;
+    enroot::import "$@" ;;
 export)
-    enroot::export "$@"
-    ;;
+    enroot::export "$@" ;;
 create)
-    enroot::create "$@"
-    ;;
+    enroot::create "$@" ;;
 start)
-    enroot::start "$@"
-    ;;
+    enroot::start "$@" ;;
 list)
-    enroot::list "$@"
-    ;;
+    enroot::list "$@" ;;
 remove)
-    enroot::remove "$@"
-    ;;
+    enroot::remove "$@" ;;
 bundle)
-    enroot::bundle "$@"
-    ;;
+    enroot::bundle "$@" ;;
 *)
-    enroot::usage
-    ;;
+    enroot::usage ;;
 esac
 
 exit 0
